### ISSUE TITLE
Upgrade skunk to 1.x

### ISSUE THREAD

**Issue by rlemaitre** [rolang/dumbo#19]
Skunk changed the tracing library in v 1.0.0-M1, making dumbo unusable with it

**Comment by rolang** [comment]
> Skunk changed the tracing library in v 1.0.0-M1, making dumbo unusable with it

thanks for reporting @rlemaitre , gonna try to prepare dumbo for the 1.x release next and check how we can keep both versions compatible.

**Comment by rolang** [comment]
@rlemaitre released [v.0.1.0](https://github.com/rolang/dumbo/releases/tag/v0.1.0) which is based on Skunk `v1.0.0-M4`.  
Going to keep Skunk v0.6.x / natchez / Scala 2.12.x compatible versions under the `v0.0.x` release series.
